# -*- coding: utf-8 -*-
"""MNIST

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l_tj9SGcVVKg1rbTnUk0kgjOcO1cg7Ux
"""

import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.utils import to_categorical

(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train = x_train / 255.0
x_test = x_test / 255.0

y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    x_train, y_train,
    epochs=5,
    batch_size=32,
    validation_split=0.1
)

test_loss, test_acc = model.evaluate(x_test, y_test)
print(f"Test Accuracy: {test_acc*100:.2f}%")

model.save("handwritten_digit_model.h5")

import numpy as np
predictions = model.predict(x_test[:5])
for i, pred in enumerate(predictions):
    print(f"Image {i+1}: Predicted Digit = {np.argmax(pred)}, Actual Digit = {np.argmax(y_test[i])}")